spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://localhost:8080/
          predicates:
            - Path=/users/**,/roles/**
        - id : r2
          uri : http://localhost:8081/
          predicates:
            - Path=/produits/**,/categories/**
        - id : r3
          uri : http://localhost:8082/
          predicates:
            - Path=/commandes/**,/commande-produits/**
        - id : r4
          uri : http://localhost:8083/
          predicates:
            - Path=/clients/**
  application:
    name: gateway-service
server:
  port: 8888
